"""Build HAS_ANALYSIS edges from survival analysis results."""
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from neo4j import Driver

logger = logging.getLogger(__name__)


def build_survival_edges(driver: Driver, processed_dir: Path) -> dict:
    """
    Create AnalysisResult nodes + HAS_ANALYSIS edges from Disease → AnalysisResult.
    Source: cd46_survival_results.csv generated by survival_analysis.py.
    """
    survival_file = processed_dir / "cd46_survival_results.csv"
    if not survival_file.exists():
        logger.warning("cd46_survival_results.csv not found — skipping survival edges")
        return {"analysis_nodes": 0, "survival_edges": 0}

    df = pd.read_csv(survival_file)
    required = {"cancer_type", "endpoint", "log_rank_p", "hazard_ratio"}
    missing = required - set(df.columns)
    if missing:
        logger.error("Survival CSV missing columns: %s", missing)
        return {"analysis_nodes": 0, "survival_edges": 0}

    created = 0
    with driver.session() as session:
        for _, row in df.iterrows():
            cancer_type = str(row["cancer_type"])
            endpoint = str(row["endpoint"])
            analysis_id = f"SUR_{cancer_type}_{endpoint}"

            hr = float(row["hazard_ratio"]) if pd.notna(row.get("hazard_ratio")) else None
            log_p = float(row["log_rank_p"]) if pd.notna(row.get("log_rank_p")) else None
            ci_lower = float(row["ci_lower"]) if "ci_lower" in row and pd.notna(row["ci_lower"]) else None
            ci_upper = float(row["ci_upper"]) if "ci_upper" in row and pd.notna(row["ci_upper"]) else None
            n_high = int(row["n_high"]) if "n_high" in row and pd.notna(row["n_high"]) else None
            n_low = int(row["n_low"]) if "n_low" in row and pd.notna(row["n_low"]) else None
            significant = bool(log_p < 0.05) if log_p is not None else False

            session.run(
                """
                MERGE (ar:AnalysisResult {analysis_id: $analysis_id})
                SET ar.cancer_type       = $cancer_type,
                    ar.endpoint          = $endpoint,
                    ar.analysis_type     = 'Kaplan-Meier + Cox PH',
                    ar.hazard_ratio      = $hr,
                    ar.ci_lower          = $ci_lower,
                    ar.ci_upper          = $ci_upper,
                    ar.log_rank_p        = $log_p,
                    ar.is_significant    = $significant,
                    ar.n_high            = $n_high,
                    ar.n_low             = $n_low,
                    ar.biomarker         = 'CD46',
                    ar.stratification    = 'Median split',
                    ar.data_source       = 'TCGA',
                    ar.updated_at        = datetime()
                WITH ar
                MATCH (d:Disease {tcga_code: $cancer_type})
                MERGE (d)-[r:HAS_ANALYSIS]->(ar)
                SET r.endpoint   = $endpoint,
                    r.is_sig     = $significant
                WITH ar
                MATCH (g:Gene {ensembl_id: 'ENSG00000117335'})
                MERGE (g)-[:HAS_SURVIVAL_RESULT]->(ar)
                """,
                analysis_id=analysis_id,
                cancer_type=cancer_type,
                endpoint=endpoint,
                hr=hr,
                ci_lower=ci_lower,
                ci_upper=ci_upper,
                log_p=log_p,
                significant=significant,
                n_high=n_high,
                n_low=n_low,
            )
            created += 1

    logger.info("Created %d AnalysisResult nodes with HAS_ANALYSIS edges", created)
    return {"analysis_nodes": created, "survival_edges": created}
