"""Build EXPRESSED_IN edges from HPA protein expression data."""
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from neo4j import Driver

logger = logging.getLogger(__name__)

LEVEL_SCORE = {"Not detected": 0, "Low": 1, "Medium": 2, "High": 3}


def build_expression_edges(driver: Driver, processed_dir: Path) -> dict:
    """
    Create EXPRESSED_IN edges between Protein → Tissue nodes.
    Also creates OVEREXPRESSED_IN edges where tumor_score > normal_score.
    Source: hpa_cd46_protein.csv generated by process_hpa.py.
    """
    hpa_file = processed_dir / "hpa_cd46_protein.csv"
    if not hpa_file.exists():
        logger.warning("hpa_cd46_protein.csv not found — skipping expression edges")
        return {"expression_edges": 0, "overexpression_edges": 0}

    df = pd.read_csv(hpa_file)
    if "tissue" not in df.columns:
        logger.error("hpa_cd46_protein.csv missing 'tissue' column")
        return {"expression_edges": 0, "overexpression_edges": 0}

    expr_edges = 0
    overexpr_edges = 0

    with driver.session() as session:
        for _, row in df.iterrows():
            tissue = str(row["tissue"])
            tumor_level = str(row.get("tumor_level", "Not detected"))
            normal_level = str(row.get("normal_level", "Not detected"))
            tumor_score = LEVEL_SCORE.get(tumor_level, 0)
            normal_score = LEVEL_SCORE.get(normal_level, 0)

            # EXPRESSED_IN edge: Protein → Tissue
            session.run(
                """
                MATCH (p:Protein {uniprot_id: 'P15529'})
                MATCH (t:Tissue {tissue_name: $tissue})
                MERGE (p)-[r:EXPRESSED_IN_TISSUE]->(t)
                SET r.tumor_level     = $tumor_level,
                    r.normal_level    = $normal_level,
                    r.tumor_score     = $tumor_score,
                    r.normal_score    = $normal_score,
                    r.data_source     = 'HPA',
                    r.updated_at      = datetime()
                """,
                tissue=tissue,
                tumor_level=tumor_level,
                normal_level=normal_level,
                tumor_score=tumor_score,
                normal_score=normal_score,
            )
            expr_edges += 1

            # Add OVEREXPRESSED_IN if tumor > normal
            if tumor_score > normal_score:
                session.run(
                    """
                    MATCH (g:Gene {ensembl_id: 'ENSG00000117335'})
                    MATCH (t:Tissue {tissue_name: $tissue})
                    MERGE (g)-[r:OVEREXPRESSED_IN]->(t)
                    SET r.fold_enrichment_rank = $fold_enrichment_rank,
                        r.data_source          = 'HPA'
                    """,
                    tissue=tissue,
                    fold_enrichment_rank=tumor_score - normal_score,
                )
                overexpr_edges += 1

    logger.info(
        "Created %d EXPRESSED_IN and %d OVEREXPRESSED_IN edges",
        expr_edges,
        overexpr_edges,
    )
    return {"expression_edges": expr_edges, "overexpression_edges": overexpr_edges}
